name: vega_innovattions_assignmen
description: PRACTICAL TEST - Flutter (Vega Innovattions)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  dio: ^4.0.6
  stream_transform: ^2.0.0
  get_it: ^7.2.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
